# Generated by Django 4.0.2 on 2022-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(null=True, related_name='categores', to='product.CategoryForOptions'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='options', to='product.Option'),
        ),
    ]
