# Generated by Django 4.0.2 on 2022-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_option_category_option_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(related_name='categores', to='product.CategoryForOptions'),
        ),
    ]
