# Generated by Django 4.0.2 on 2022-02-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_option_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryforoptions'),
        ),
    ]
