# Generated by Django 4.0.2 on 2022-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_option_category_option_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categores', to='product.CategoryForProduct'),
        ),
    ]
