# Generated by Django 4.0.2 on 2022-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryforproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
