# Generated by Django 4.0.2 on 2022-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_categoryforproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
