# Generated by Django 4.0.2 on 2022-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_cont',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
