# Generated by Django 4.0.2 on 2022-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_sales_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_cont',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
