# Generated by Django 4.0.2 on 2022-02-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_sales_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_cont',
            new_name='sales_count',
        ),
    ]
