# Generated by Django 4.0.2 on 2022-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_sales_cont_product_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_peresen',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
