# Generated by Django 4.0.2 on 2022-04-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('payment', models.BooleanField(default=False)),
                ('price_paid', models.IntegerField(default=0)),
                ('trackingcode', models.BigIntegerField()),
                ('confirm', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='product.Product')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
