# Generated by Django 4.0.2 on 2022-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_address_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
