# Generated by Django 4.0.2 on 2022-04-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_send_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='send',
            new_name='confirm',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='post',
        ),
    ]
